name: Vincent's Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Step 1
        run: echo 'This is the first step.'

      - name: Step 2
        run: echo 'This is the second step.'
  
  job_2:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3

      - name: Step 1
        run: echo 'This is the first step of the second job.'